### ISSUE TITLE
Install Guide

### ISSUE THREAD

**Issue by st0nec0ld** [xMordax/ansible-role-librespot#1]
Hi,

can you plz make a guide how to use/install?

thx

**Comment by xMordax** [comment]
Will write a bit more detailed documentation about how to install and deploy apps with Ansible :) but for a start, you can also take a loot at https://docs.ansible.com, in their documentation they explain how to install and use Ansible.

**Comment by xMordax** [comment]
Added better documentation in the following commit:
77d34cab355ab6ebdb2bf01323dfc0272b9f140f
